provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  pytag-fn:
    lang: python3
    handler: ./pytag-fn
    image: embano1/pytag-fn:0.1
    environment:
      VC: 
      VC_USERNAME: 
      VC_PASSWORD: 
      TAG_URN: 
      TAG_ACTION: 
    annotations:
      topic: vm.powered.on